import React from 'react'
 
const Related = () => {
  return (
    <div className="detail__relatedWrapper">
      <ul className="detail__related">
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
        <li>
          <img
            src="https://www.themoviedb.org/t/p/w250_and_h141_face/kSaZZO9LIHNhpGvHmmbI6D6RZw5.jpg"
            alt="teste"
          />
        </li>
      </ul>
    </div>
  );
}
 
export default Related;
